version: "3"
services:
  inceptioner:
    build: .
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.3"
          memory: 1G
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8080"
    networks:
      - inceptioner_net
networks:
  inceptioner_net: